### ISSUE TITLE
按教程部署后没有加速

### ISSUE THREAD

**Issue by M1ddlzh** [ImSingee/hammal#3]
大佬方便贴一下worker中的js代码吗，按照您的文章部署后没有加速。
是js小白，不太清楚如何调试😁

**Comment by MagicGopher** [comment]
我也是没怎么看懂文档，就很尴尬😂

**Comment by hp0912** [comment]
没有加速效果 +1  域名能正常 ping 通

**Comment by M1ddlzh** [comment]
> 大佬方便贴一下worker中的js代码吗，按照您的文章部署后没有加速。 是js小白，不太清楚如何调试😁

哦代码没问题，我对cloudflare workers使用不太熟悉，之前只改了路由
<img width="756" alt="image" src="https://github.com/ImSingee/hammal/assets/45971465/53a379bd-4478-4fb9-b982-ce7bb26f5768">
还需要改一下自定义域：
<img width="940" alt="image" src="https://github.com/ImSingee/hammal/assets/45971465/bd14e4a2-242a-42d3-b1bb-e6c1dd8c41ac">
